// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6jYuYH9-4x2RMcFUz1KgFSnTTlENiVzI',
    appId: '1:481178445399:web:2cb4fe64a054c1f35ce512',
    messagingSenderId: '481178445399',
    projectId: 'el-patool-c5476',
    authDomain: 'el-patool-c5476.firebaseapp.com',
    storageBucket: 'el-patool-c5476.firebasestorage.app',
    measurementId: 'G-8Y4ETC1RFY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNxvuR0IJfGttLPBYsqkkB8CZhfmSLFg8',
    appId: '1:481178445399:android:ddc87f0713228a9f5ce512',
    messagingSenderId: '481178445399',
    projectId: 'el-patool-c5476',
    storageBucket: 'el-patool-c5476.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3A7fIoLXLbGlaORNSJOwlyT1_Tm0sUaM',
    appId: '1:481178445399:ios:449ac55ca79e52685ce512',
    messagingSenderId: '481178445399',
    projectId: 'el-patool-c5476',
    storageBucket: 'el-patool-c5476.firebasestorage.app',
    iosBundleId: 'com.example.elPatol',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3A7fIoLXLbGlaORNSJOwlyT1_Tm0sUaM',
    appId: '1:481178445399:ios:449ac55ca79e52685ce512',
    messagingSenderId: '481178445399',
    projectId: 'el-patool-c5476',
    storageBucket: 'el-patool-c5476.firebasestorage.app',
    iosBundleId: 'com.example.elPatol',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD6jYuYH9-4x2RMcFUz1KgFSnTTlENiVzI',
    appId: '1:481178445399:web:429622b43e6e16a05ce512',
    messagingSenderId: '481178445399',
    projectId: 'el-patool-c5476',
    authDomain: 'el-patool-c5476.firebaseapp.com',
    storageBucket: 'el-patool-c5476.firebasestorage.app',
    measurementId: 'G-H9451LWPRG',
  );
}
